---

- name: Create the runtime dir
  file:
    path: "{{ query_exporter_config_location }}"
    state: directory
    mode: '0755'

- name: Materialize Query Exporter's config
  template:
    src: config.yaml.j2
    dest: "{{ query_exporter_config_location }}/config.yaml"
    mode: "755"
  register: query_exporter_config_result

- name: Query exporter service restart
  systemd:
    daemon_reload: true
  when:
    - query_exporter_config_result is defined
    - query_exporter_config_result.changed
  tags:
    - skip_ansible_lint
