---
- name: Create the Query Exporter group
  group:
    name: "{{ __query_exporter_group }}"
    state: present
    system: true

- name: Create the Query Exporter user
  user:
    name: "{{ __query_exporter_user }}"
    groups: "{{ __query_exporter_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- block:
    - name: Download query_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus/query_exporter/releases/download/v{{ query_exporter_version }}/query_exporter-{{ query_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
        dest: "/tmp/query_exporter-{{ query_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
        checksum: "sha256:{{ __query_exporter_checksum }}"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack query_exporter binary
      become: false
      unarchive:
        src: "/tmp/query_exporter-{{ query_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/query_exporter-{{ query_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/query_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate query_exporter binaries
      copy:
        src: "/tmp/query_exporter-{{ query_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/query_exporter"
        dest: "/usr/local/bin/query_exporter"
        mode: 0755
        owner: root
        group: root
      notify:
        - restart query exporter
      when: not ansible_check_mode
  when: query_exporter_binary_local_dir | length == 0

- name: propagate locally distributed query_exporter binary
  copy:
    src: "{{ query_exporter_binary_local_dir }}/query_exporter"
    dest: "/usr/local/bin/query_exporter"
    mode: 0755
    owner: root
    group: root
  when: query_exporter_binary_local_dir | length > 0
  notify: restart query exporter

- name: Copy the query_exporter systemd service file
  template:
    src: query_exporter.service.j2
    dest: /etc/systemd/system/query_exporter.service
    owner: root
    group: root
    mode: 0644
  no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
  notify:
    - restart query exporter
