---

dependency:
    name: galaxy
    options:
        force: true
        ignore-certs: false
        ignore-errors: false
driver:
    name: lxd
lint:
    name: yamllint
platforms:

    - name: test-query-exporter-bionic
      nested: "false"
      privileged: "false"
      image: "ubuntu/bionic/amd64"

    - name: test-query-exporter-focal
      nested: "false"
      privileged: "false"
      image: "ubuntu/focal/amd64"

provisioner:
    config_options:
        defaults:
            bin_ansible_callbacks: true
            display_ok_hosts: false
            display_skipped_hosts: false
            forks: 50
            internal_poll_interval: 0.001
            stdout_callback: yaml
            callbacks_enabled: profile_tasks
            strategy: free
        ssh_connection:
            pipelining: true
    env:
        ANSIBLE_ROLES_PATH:
            $ephemeral_directory/roles/:../../roles/
    lint:
        name: ansible-lint
    name: ansible

scenario:
    name: lxd-ci

verifier:
    directory: ../../tests/integration
    name: goss
    lint:
        name: yamllint
