---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bionic
    pre_build_image: true
    image: quay.io/paulfantom/molecule-systemd:ubuntu-18.04
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: focal
    pre_build_image: true
    image: quay.io/paulfantom/molecule-systemd:ubuntu-20.04
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: ../local-lxd/playbook.yml  # DRY
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  directory: ../../tests/integration
  name: goss
  lint:
    name: yamllint
