---
- name: Prepare
  hosts: all
  tasks:
    - name: Gather variables for each operating system
      debug:
        var: ansible_distribution
    - name: Install query server
      package:
        name: "mariadb-server"
        state: present
    - name: Start query server
      systemd:
        name: "{{ item }}"
        state: started
      ignore_errors: true
      with_items:
        - mysql
        - mysqld
        - mariadb
