---
goss_version: v0.3.7
goss_arch: amd64
goss_bin: /usr/local/bin/goss
goss_sha256sum: 357f5c7f2e7949b412bce44349cd32ab19eb3947255a8ac805f884cc2c326059.
goss_test_directory: /tmp/molecule/goss
goss_format: documentation

query_exporter_service_name: query_exporter
query_exporter_port: 9560
query_exporter_web_listen_address: "0.0.0.0"
