---

name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish | Ansible Galaxy"]
    types:
      - completed

jobs:
  cd-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('local-requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r local-requirements.txt

      - name: Create molecule cache foder
        run: mkdir -p /tmp/molecule_ephemeral/${{ github.run_id }}

      - name: Init LXD
        uses: bonddim/action-lxd-init@v1

      - name: Test with molecule
        run: molecule test --scenario-name lxd-cd
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule_ephemeral/${{ github.run_id }}