---

name: CI

on:
  workflow_run:
    workflows: ["Ansible Lint"]
    branches: [main]
    types:
      - completed

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - local-lxd
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('local-requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r local-requirements.txt

      - name: Create molecule cache foder
        run: mkdir -p /tmp/molecule_ephemeral/${{ github.run_id }}

      - name: Test with molecule
        uses: bonddim/action-lxd-init@v1
        run: molecule test --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule_ephemeral/${{ github.run_id }}